name: piano-duo

services:
  piano-duo-web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8081/v1/api}
        VITE_PORT: ${VITE_PORT:-8080}
    image: piano-duo-images/web
    container_name: piano-duo-web
    ports:
      - "8080:8080"
    depends_on:
      - piano-duo-api
      - piano-duo-strapi
    networks:
      - piano-duo-network

  piano-duo-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: piano-duo-images/api
    container_name: piano-duo-api
    ports:
      - "8081:8081"
    env_file:
      - ./api/.env
    depends_on:
      - piano-duo-strapi
    networks:
      - piano-duo-network

  piano-duo-strapi:
    build:
      context: ./strapi
      dockerfile: Dockerfile
    image: piano-duo-images/strapi
    container_name: piano-duo-strapi
    ports:
      - "8082:8082"
    env_file:
      - ./strapi/.env
    networks:
      - piano-duo-network

networks:
  piano-duo-network:
    driver: bridge
