steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
      - '.'
    id: 'Build'
    dir: 'api'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
    id: 'Push'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image=$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'
      - '--region=$_DEPLOY_REGION'
      - '--platform=managed'
      - '--quiet'
      - '--set-env-vars'
      - |
        FASTIFY_PORT=${_FASTIFY_PORT},
        FASTIFY_INTERFACE=${_FASTIFY_INTERFACE},
        STRAPI_URL=${_STRAPI_URL},
        STRAPI_TOKEN=${_STRAPI_TOKEN},
        BREVO_API_URL=${_BREVO_API_URL},
        BREVO_API_KEY=${_BREVO_API_KEY},
        EMAIL_DESTINATION=${_EMAIL_DESTINATION},
        EMAIL_FROM=${_EMAIL_FROM},
        NODE_ENV=production
    id: 'Deploy'

images:
  - '$_AR_HOSTNAME/$PROJECT_ID/$_AR_REPOSITORY/$_SERVICE_NAME:$COMMIT_SHA'

substitutions:
  _SERVICE_NAME: piano-duo-api
  _DEPLOY_REGION: europe-west1
  _AR_HOSTNAME: europe-west1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy

options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
